### LISTAR USUÁRIOS
GET http://localhost:3000/usuarios

###
GET http://localhost:3000/musicas/1


### Listar Músicas
GET http://localhost:3000/musicas

###
GET http://localhost:3000/comentarios/1
###
GET http://localhost:3000/comentarios

### CADASTRAR USUÁRIO
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "teste2",
    "email": "teste2@gmail.com",
    "senha": "123456"
}

###

POST http://localhost:3000/comentarios
Content-Type: application/json

{
    "texto": "Comentário criado pelo teste.http",
    "id_usuario": 1,
    "id_musica": 1
}

###

### TESTE DE CAMPO VAZIO
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "",
    "email": "",
    "senha": ""
}

###

### ATUALIZAR USUÁRIO
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "Israell Atualizado",
    "email": "israel@email.com",
    "senha": "123"
}

###

### REMOVER USUÁRIO
DELETE http://localhost:3000/usuarios/1